export const INCREMENT_ENTHUSIASM: string = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;
export const DECREMENT_ENTHUSIASM: string = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const INPROGRESS_LOGIN: string = 'INPROGRESS_LOGIN';
export type INPROGRESS_LOGIN = typeof INPROGRESS_LOGIN;
export const SUCCESS_LOGIN: string = 'SUCCESS_LOGIN';
export type SUCCESS_LOGIN = typeof SUCCESS_LOGIN;
export const FAILURE_LOGIN: string = 'FAILURE_LOGIN';
export type FAILURE_LOGIN = typeof FAILURE_LOGIN;
